// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Messages is the predicate function for messages builders.
type Messages func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
