// Code generated by ent, DO NOT EDIT.

package ent

import (
	"GoTrain/BackEnd/ent/messages"
	"GoTrain/BackEnd/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	messagesFields := schema.Messages{}.Fields()
	_ = messagesFields
	// messagesDescCreatedAt is the schema descriptor for created_at field.
	messagesDescCreatedAt := messagesFields[1].Descriptor()
	// messages.DefaultCreatedAt holds the default value on creation for the created_at field.
	messages.DefaultCreatedAt = messagesDescCreatedAt.Default.(func() time.Time)
}
