// Code generated by ent, DO NOT EDIT.

package messages

import (
	"GoTrain/BackEnd/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Messages {
	return predicate.Messages(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Messages {
	return predicate.Messages(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Messages {
	return predicate.Messages(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Messages {
	return predicate.Messages(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Messages {
	return predicate.Messages(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Messages {
	return predicate.Messages(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Messages {
	return predicate.Messages(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Messages {
	return predicate.Messages(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Messages {
	return predicate.Messages(sql.FieldLTE(FieldID, id))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Messages {
	return predicate.Messages(sql.FieldEQ(FieldContent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Messages {
	return predicate.Messages(sql.FieldEQ(FieldCreatedAt, v))
}

// USERID applies equality check predicate on the "USER_ID" field. It's identical to USERIDEQ.
func USERID(v int) predicate.Messages {
	return predicate.Messages(sql.FieldEQ(FieldUSERID, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Messages {
	return predicate.Messages(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Messages {
	return predicate.Messages(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Messages {
	return predicate.Messages(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Messages {
	return predicate.Messages(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Messages {
	return predicate.Messages(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Messages {
	return predicate.Messages(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Messages {
	return predicate.Messages(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Messages {
	return predicate.Messages(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Messages {
	return predicate.Messages(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Messages {
	return predicate.Messages(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Messages {
	return predicate.Messages(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Messages {
	return predicate.Messages(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Messages {
	return predicate.Messages(sql.FieldContainsFold(FieldContent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Messages {
	return predicate.Messages(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Messages {
	return predicate.Messages(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Messages {
	return predicate.Messages(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Messages {
	return predicate.Messages(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Messages {
	return predicate.Messages(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Messages {
	return predicate.Messages(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Messages {
	return predicate.Messages(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Messages {
	return predicate.Messages(sql.FieldLTE(FieldCreatedAt, v))
}

// USERIDEQ applies the EQ predicate on the "USER_ID" field.
func USERIDEQ(v int) predicate.Messages {
	return predicate.Messages(sql.FieldEQ(FieldUSERID, v))
}

// USERIDNEQ applies the NEQ predicate on the "USER_ID" field.
func USERIDNEQ(v int) predicate.Messages {
	return predicate.Messages(sql.FieldNEQ(FieldUSERID, v))
}

// USERIDIn applies the In predicate on the "USER_ID" field.
func USERIDIn(vs ...int) predicate.Messages {
	return predicate.Messages(sql.FieldIn(FieldUSERID, vs...))
}

// USERIDNotIn applies the NotIn predicate on the "USER_ID" field.
func USERIDNotIn(vs ...int) predicate.Messages {
	return predicate.Messages(sql.FieldNotIn(FieldUSERID, vs...))
}

// USERIDGT applies the GT predicate on the "USER_ID" field.
func USERIDGT(v int) predicate.Messages {
	return predicate.Messages(sql.FieldGT(FieldUSERID, v))
}

// USERIDGTE applies the GTE predicate on the "USER_ID" field.
func USERIDGTE(v int) predicate.Messages {
	return predicate.Messages(sql.FieldGTE(FieldUSERID, v))
}

// USERIDLT applies the LT predicate on the "USER_ID" field.
func USERIDLT(v int) predicate.Messages {
	return predicate.Messages(sql.FieldLT(FieldUSERID, v))
}

// USERIDLTE applies the LTE predicate on the "USER_ID" field.
func USERIDLTE(v int) predicate.Messages {
	return predicate.Messages(sql.FieldLTE(FieldUSERID, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Messages {
	return predicate.Messages(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.Users) predicate.Messages {
	return predicate.Messages(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Messages) predicate.Messages {
	return predicate.Messages(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Messages) predicate.Messages {
	return predicate.Messages(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Messages) predicate.Messages {
	return predicate.Messages(sql.NotPredicates(p))
}
